$schema: "../generation-config-schema/guten-tag-generation-config.schema.yaml"

timeseries:
- name: demo
  length: 1000
  base-oscillations:
  - kind: sine
    frequency: 4.0
    amplitude: 1.0
    variance: 0.05
  anomalies:
  - position: middle
    length: 50
    channel: 0
    kinds:
    - kind: pattern
      parameters:
        sinusoid_k: 10.0
        cbf_pattern_factor: 1.0
  - position: end
    length: 10
    channel: 0
    kinds:
    - kind: amplitude
      parameters:
        amplitude_factor: 1.5
