$schema: "generation-config-schema/guten-tag-generation-config.schema.yaml"

timeseries:
  - name: bleed_air
    length: 10000
    base_oscillations:
      - kind: sine
        variance: 0.05
      - kind: correlation
        formula: "$0 ** 2"
    anomalies:
      - position: beginning
        length: 100
        channel: 0
        kinds:
          - kind: pattern
            parameters:
              sinusoid_k: 10.0
      - position: end
        length: 100
        channel: 1
        kinds:
          - kind: platform
            parameters:
              value: 0.0

#  - name: demo
#    length: 1000
#    channels: 1
#    semi-supervised: true
#    supervised: true
#    base_oscillation:
#      kind: sine
#      frequency: 4.0
#      amplitude: 1.0
#      variance: 0.05
#    anomalies:
#      - position: middle
#        length: 50
#        kinds:
#          - kind: pattern
#            parameters:
#              sinusoid_k: 10.0
#              cbf_pattern_factor: 1.0
#      - position: end
#        length: 10
#        kinds:
#          - kind: amplitude
#            parameters:
#              amplitude_factor: 1.5
