timeseries:
  - base-oscillation: &base
      kind: "ecg"
      length: 1000
      channels: 1
      with-train: false
      frequency: 10.0
      amplitude: 1.0
      variance: 0.0
      avg-pattern-length: 0
      variance-pattern-length: 10
      heart-rate: 60
    anomalies:
      - position: "middle"
        length: 100
        kinds:
          - name: "pattern"
            parameters: {}
  #- base-oscillation: &sinus-base
  #    kind: "sinus"
  #    length: 1000
  #    channels: 1
  #    frequency: 20.0
  #    amplitude: 1.0
  #    variance: 0.0
  #    avg-pattern-length: 10
  #    variance-pattern-length: 10
  #    heart-rate: 60
  #    with-train: false
  #  anomalies:
  #    - position: "middle"
  #      length: 200
  #      kinds:
  #        - name: "pattern-shift"
  #          parameters:
  #            shift_factor: 0.1
  #            transition_window: 75
