# base definitions
base:
  - base-oscillation: &base
      length: 10000
      channels: 1
      with-train: true
      frequency: 100.0
      amplitude: 1.0
      variance: 0.1
sinus:
  - base-oscillation: &sinus-0
      <<: *base
      kind: "sinus"
  - base-oscillation: &sinus-1
      <<: *sinus-0
      frequency: 75.1
      amplitude: 2.5
      offset: -2.0
  - base-oscillation: &sinus-2
      <<: *sinus-0
      frequency: 125.4
      amplitude: 0.5
      offset: 1.3
  - base-oscillation: &sinus-linear-trend
      <<: *sinus-1
  - base-oscillation: &sinus-other-trend
      <<: *sinus-2
noisy_sinus: {}
random_walk:
  - base-oscillation: &rw-0
      <<: *base
      kind: "random_walk"
      variance: 0.0
  - base-oscillation: &rw-1
      <<: *rw-0
      amplitude: 2.5
      offset: -2.0
  - base-oscillation: &rw-2
      <<: *rw-0
      amplitude: 0.5
      offset: 1.3
  - base-oscilaltion: &rw-no-smoothing # TODO: variance -> smoothing
      <<: *rw-0
      variance: 0.0
  - base-oscillation: &rw-linear-trend
      <<: *rw-1
  - base-oscillation: &rw-other-trend
      <<: *rw-2
cylinder_bell_funnel: {}
ecg: {}
anomaly_kinds:
  - &local-extremum
    name: "extremum"
    parameters:
      min: true
      local: true
      context_window: 10
  - &global-extremum
    name: "extremum"
    parameters:
      min: false
      local: false
  - &frequency
    name: "frequency"
    parameters:
      factor: 2.0
  - &mean
    name: "mean"
    parameters:
      offset: 1.0
  - &pattern
    name: "pattern"
    parameters:
      sinusoid_k: 10.0
      factor: 2.0
  - &pattern-shift
    name: "pattern-shift"
    parameters:
      shift_factor: 0.5
      transition_window: 10
  - &platform
    name: "platform"
    parameters:
      value: 0.0
  - &variance-larger
    name: "variance"
    parameters:
      value: 0.3
  - &variance-smaller
    name: "variance"
    parameters:
      value: 0.03
# declaration
timeseries:
  # sinus
  - base-oscillation: *sinus-0
    anomalies:
      - position: "beginning"
        length: 100
        channel: 0
        kinds:
          - <<: *variance-smaller
  - base-oscillation: *sinus-1
    anomalies:
      - position: "beginning"
        length: 100
        channel: 0
        kinds:
          - <<: *variance-larger
