timeseries:
  - base-oscillation: &sinus-base
      kind: "sinus"
      length: 1000
      channels: 1
      frequency: 20.0
      amplitude: 1.0
      variance: 0.0
      avg-pattern-length: 10
      variance-pattern-length: 10
      heart-rate: 60
      with-train: false
    anomalies:
      - position: "middle"
        length: 200
        kinds:
          - name: "platform"
            parameters:
              value: 0.0

          - name: "variance"
            parameters:
              value: 0.0
